# Generated by Django 5.0.2 on 2025-02-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_image', models.ImageField(upload_to='aboutimage/')),
                ('mobile_image', models.ImageField(upload_to='aboutimage/')),
                ('title', models.CharField(max_length=150)),
                ('details', models.TextField(max_length=5500)),
            ],
            options={
                'verbose_name_plural': '3. About_Us',
            },
        ),
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.ImageField(upload_to='amenitiesimage/')),
                ('title', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': '5. Amenities',
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typology', models.CharField(max_length=150)),
                ('rera_carpet_area', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': '5. Configuration',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('Views', 'Views'), ('Amenities', 'Amenities'), ('Interiors', 'Interiors'), ('Exterior', 'Exterior'), ('Plans', 'Plans')], max_length=100)),
                ('web_image', models.ImageField(upload_to='galleryimage/')),
                ('mobile_image', models.ImageField(upload_to='galleryimage/')),
                ('title', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': '6. Gallery',
            },
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_image', models.ImageField(upload_to='overviewimage/')),
                ('mobile_image', models.ImageField(upload_to='overview/')),
                ('title', models.CharField(max_length=150)),
                ('details', models.TextField(max_length=5500)),
            ],
            options={
                'verbose_name_plural': '3. About_Us',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('keywords', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('configuration_bg', models.ImageField(upload_to='logo/')),
                ('logo', models.ImageField(upload_to='logo/')),
                ('logo_2', models.ImageField(upload_to='logo/')),
                ('icon', models.ImageField(upload_to='images/')),
                ('color', models.CharField(max_length=150)),
                ('cuntact_no', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=1150)),
            ],
            options={
                'verbose_name_plural': '1. Header',
            },
        ),
        migrations.CreateModel(
            name='Unique_Selling_Proposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.ImageField(upload_to='uspimage/')),
                ('title', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': '4. Unique Selling Proposition',
            },
        ),
        migrations.CreateModel(
            name='Web_Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_image', models.ImageField(upload_to='sliderimage/')),
                ('mobile_image', models.ImageField(upload_to='sliderimage/')),
                ('title', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': '2. Web Slider',
            },
        ),
    ]
