# Generated by Django 5.0.2 on 2025-02-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_us',
            options={'verbose_name_plural': '4. About_Us'},
        ),
        migrations.AlterModelOptions(
            name='amenities',
            options={'verbose_name_plural': '7. Amenities'},
        ),
        migrations.AlterModelOptions(
            name='configuration',
            options={'verbose_name_plural': '6. Configuration'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': '7. Gallery'},
        ),
        migrations.AlterModelOptions(
            name='overview',
            options={'verbose_name_plural': '3. Overview'},
        ),
        migrations.AlterModelOptions(
            name='unique_selling_proposition',
            options={'verbose_name_plural': '5. Unique Selling Proposition'},
        ),
        migrations.AddField(
            model_name='unique_selling_proposition',
            name='icone2',
            field=models.ImageField(blank=True, null=True, upload_to='uspimage/'),
        ),
        migrations.AddField(
            model_name='unique_selling_proposition',
            name='title2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
