# Generated by Django 5.0.2 on 2025-02-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_about_us_options_alter_amenities_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='icone2',
            field=models.ImageField(blank=True, null=True, upload_to='uspimage/'),
        ),
        migrations.AddField(
            model_name='amenities',
            name='title2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
