# Generated by Django 5.0.2 on 2025-03-01 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_setting_site_ddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='site_ddress',
            new_name='site_address',
        ),
    ]
