# Generated by Django 5.0.2 on 2025-03-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_site_ddress_setting_site_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='price',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
    ]
