# Generated by Django 5.0.1 on 2025-03-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_configuration_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': '8. Gallery'},
        ),
        migrations.AddField(
            model_name='setting',
            name='googletagmanager',
            field=models.CharField(blank=True, max_length=1150, null=True),
        ),
    ]
