# Generated by Django 5.0.1 on 2025-04-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contactmessage_alter_setting_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='mobile',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
