# Generated by Django 5.0.2 on 2025-05-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_contactmessage_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookingopen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=150)),
                ('at', models.CharField(max_length=255)),
                ('by', models.CharField(max_length=255)),
                ('landp_arcel', models.CharField(max_length=255)),
                ('possession', models.CharField(max_length=255)),
                ('spot_booking_offers', models.CharField(max_length=255)),
                ('early_buy_discounts', models.CharField(max_length=255)),
                ('flexipay_for_first', models.CharField(max_length=255)),
                ('luxurious', models.CharField(max_length=255)),
                ('priceing', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '10. project_name',
            },
        ),
        migrations.CreateModel(
            name='Welcometo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('details', models.TextField(max_length=5500)),
                ('readmore', models.TextField(max_length=5500)),
            ],
            options={
                'verbose_name_plural': '5. Welcome To',
            },
        ),
    ]
