# Generated by Django 5.0.2 on 2025-05-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_bookingopen_welcometo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': '12. Location',
            },
        ),
        migrations.CreateModel(
            name='Maharera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_image', models.ImageField(upload_to='overviewimage/')),
                ('title', models.CharField(max_length=150)),
                ('maharera_no', models.CharField(blank=True, max_length=50)),
                ('details', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name_plural': '13. Maharera',
            },
        ),
        migrations.AlterModelOptions(
            name='bookingopen',
            options={'verbose_name_plural': '10. Booking Open'},
        ),
        migrations.AlterModelOptions(
            name='welcometo',
            options={'verbose_name_plural': '11. Welcome To'},
        ),
        migrations.AddField(
            model_name='bookingopen',
            name='floors',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
