# Generated by Django 5.0.2 on 2025-05-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_gallery_mobile_image_remove_gallery_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='virtual_site_visit',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
