# Generated by Django 5.0.2 on 2025-05-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_setting_virtual_site_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reraaditional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_registered', models.CharField(max_length=350)),
                ('Government_RERA_Authorised_Advertiser', models.CharField(max_length=500)),
                ('RERA_Project_Registration_No', models.CharField(max_length=500)),
                ('Site_Address', models.CharField(max_length=350)),
                ('Contact_Us', models.CharField(max_length=500)),
                ('Disclaimer', models.CharField(max_length=1500)),
            ],
            options={
                'verbose_name_plural': '14. RERA Aditional;',
            },
        ),
    ]
