# Generated by Django 5.0.2 on 2025-05-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_reraaditional'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='website_link',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
