# Generated by Django 5.0.2 on 2025-05-17 07:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_setting_website_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='privacy_policy',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
