# Generated by Django 5.0.1 on 2025-05-23 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_contact_response'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
