# Generated by Django 5.0.1 on 2025-05-23 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_response_delete_homeresponse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reraaditional',
            options={'verbose_name_plural': '14. RERA Aditional'},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'verbose_name_plural': 'Responses'},
        ),
    ]
