# Generated by Django 5.0.1 on 2025-05-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_reraaditional_options_alter_response_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={},
        ),
        migrations.RemoveField(
            model_name='response',
            name='message',
        ),
        migrations.AddField(
            model_name='response',
            name='phone',
            field=models.CharField(default='Not Provided', max_length=15),
            preserve_default=False,
        ),
    ]
