# Generated by Django 5.0.1 on 2025-05-24 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_response_created_at_response_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
    ]
