# Generated by Django 5.0.1 on 2025-05-24 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_delete_response'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name_plural': '1. Contact'},
        ),
    ]
